[package]
name = "tetanux"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
httparse = "1.10.1"
http-request = "8.91.29"
url = "2.5.7"
clap = { version = "4.5.51", features = ["derive"] }
lazy_static = "1.5.0"
ipnet = "2.11.0"

# https://github.com/hickory-dns/hickory-dns/issues/2249
hickory-resolver = { version = "0.25.2", features = ["https-aws-lc-rs", "webpki-roots"] }